# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x06stress\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\x04Text\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x0c\n\x04text\x18\x02 \x01(\t2<\n\x06Server\x12\x32\n\x08get_text\x12\x16.google.protobuf.Empty\x1a\x0c.stress.Text\"\x00\x62\x06proto3')



_TEXT = DESCRIPTOR.message_types_by_name['Text']
Text = _reflection.GeneratedProtocolMessageType('Text', (_message.Message,), {
  'DESCRIPTOR' : _TEXT,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:stress.Text)
  })
_sym_db.RegisterMessage(Text)

_SERVER = DESCRIPTOR.services_by_name['Server']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEXT._serialized_start=53
  _TEXT._serialized_end=92
  _SERVER._serialized_start=94
  _SERVER._serialized_end=154
# @@protoc_insertion_point(module_scope)
